### ISSUE TITLE
Snippet not working on [dot]JSX file.

### ISSUE THREAD

**Issue by sipsipsip** [xabikos/vscode-react#10]
I just install this snippet on latest visual studio code, I'm on mac. This snippet works on file with .js extension but not appear on .jsx files.

**Comment by xabikos** [comment]
What is the language indication in bottom right corner? It should be either JavaScript or JavaScript React

![image](https://cloud.githubusercontent.com/assets/487416/13882237/f1c86528-ed24-11e5-8c5e-5ea5169b935a.png)

**Comment by sipsipsip** [comment]
![screen shot 2016-03-21 at 08 35 31](https://cloud.githubusercontent.com/assets/15917886/13908906/ab73ee40-ef3f-11e5-8b81-5492dc9093b7.png)

I use JSX bro like above

**Comment by sipsipsip** [comment]
Ok, I think I'll just use javascript react

**Comment by xabikos** [comment]
I think that the safest option. JSX is something that existed in the first releases of VS Code if I am not mistaken

**Comment by iRoachie** [comment]
@xabikos is it possible to allow it to use for the JSX language. The reason is because the javascript react one doesn't show syntax highlighting in the render method.

**Comment by xabikos** [comment]
I will publish a new version in the coming days that will add support for JSX language. I guess it won't cause an issue as JSX language is something you need to install an extension and it isn't come preinstall with Code.

**Comment by xabikos** [comment]
Done!
