### ISSUE TITLE
Whats the name of plugin 

### ISSUE THREAD

**Issue by sunitJindal** [xabikos/vscode-react#12]
Cannot find the name of plugin which i should use while executing command `ext install`.

I tried using `ext install vscode-react` but no result was returned. Currently using code v1.0.0

**Comment by xabikos** [comment]
What you can do is type just `ext install` then hit enter and you will see the list with all extensions. After that just type `React` and select this extension and press enter once again.

**Comment by sunitJindal** [comment]
@xabikos thanks... found it. Writing `Reactjs` gives better result.
