### ISSUE TITLE
update template

### ISSUE THREAD

**Issue by fegg** [xabikos/vscode-react#14]
hello, I want to edit **rcc** command generate template

because I not like this:

`import {Component} from 'react'`

I want to this:

`import { Component } from react`

haha~ how to edit it I want to know? Thanks ^0^

**Comment by fegg** [comment]
= .= Sorry, I find React snippets in 

`${Home}/.vscode/extensions/xabikos.ReactSnippets-0.4.1`

I has update it. thanks share your snippets.~

**Comment by xabikos** [comment]
Yes I know that this is a personal preference and whatever the choice half of the people won't like it. 

By the way there is a new version of the snippets as I see you use the 0.4.1 In the new version the JavaScript snippets were removed and you have to install explicitly the JavaScript snippets extension.
