### ISSUE TITLE
support contextTypes declaration?

### ISSUE THREAD

**Issue by vkammerer** [xabikos/vscode-react#18]

**Comment by xabikos** [comment]
I will prepare and publish a new version with context type. Thank you for the idea @vkammerer

**Comment by vkammerer** [comment]
Ok thank you @xabikos!

Also, on another subject, would it be possible to add spaces when we import a specific object from a module? Like for example:
`import React, { Component } from 'react';`
instead of:
`import React, {Component} from 'react';`

It is more legible, and it seems like most people do it this way.
Importing it without spaces is actually seen as an error if you use eslint with the "airbnb" preset. You can see here that they use spaces for import statements:
https://github.com/airbnb/javascript#modules

**Comment by xabikos** [comment]
@vkammerer could you give an example on how the context type declaration could look like?

And about the spacing I created an [issue](https://github.com/xabikos/vscode-javascript/issues/17) to the correct Github repo
