### ISSUE TITLE
Some snippets don't work

### ISSUE THREAD

**Issue by yantakus** [xabikos/vscode-react#19]
Hi. Just have check with the latest version of VSCode (1.8.0) and the latest version of the plugin (1.2.0), the following snippets don't work:

```
props→	this.props
state→	this.state
```

**Comment by xabikos** [comment]
Hello @web2style 

I am on windows 10 VS Code 1.8.1 (latest stable) 

![image](https://cloud.githubusercontent.com/assets/487416/21503225/7dc0ef8c-cc5e-11e6-9bf0-ab62f14b6c7e.png)
and the snippets are ok. The only difference is that now for the `props` snippet you need to choose the one coming from React Snippets and not the suggested one that appears first in the list as it shown below

![image](https://cloud.githubusercontent.com/assets/487416/21503266/d0da6554-cc5e-11e6-8a2b-cc574a997732.png)

For the `state` snippet I don't see any problem. I will close this but please feel free to open it again if you face any issues.
