### ISSUE TITLE
Respect eslint config when inserting snippets

### ISSUE THREAD

**Issue by yantakus** [xabikos/vscode-react#20]
This would be great to format snippets according to existing eslint rules of the project.

Because for now, when I insert a snippet I have lots of eslint warnings:

![index1 js - first-agenda 2016-12-15 11-00-14](https://cloud.githubusercontent.com/assets/2179726/21216073/d8f1cfaa-c2b5-11e6-9715-d981a3e3021e.png)

So I have to save the file for eslint plugin to fix all of them:

![index1 js - first-agenda 2016-12-15 11-00-36](https://cloud.githubusercontent.com/assets/2179726/21216096/ec5fb6ba-c2b5-11e6-9ff7-fa8dbb0943bf.png)

This happens because I have `"eslint.autoFixOnSave": true` setting enabled.

If it happened automatically (before inserting the snippet into the editor), it would be awesome.

Can we add it, what do you think?

**Comment by xabikos** [comment]
Hello @web2style and sorry for the late reply. 

I see your problem but we can't do something about this unfortunately. When writing the snippets you don't have access to the eslint configuration or something similar. The only option you have is to specify some placeholders which you can fill and on which places the cursor will move when hitting TAB.
