### ISSUE TITLE
Make semicolons optional 

### ISSUE THREAD

**Issue by dearfrankg** [xabikos/vscode-react#22]
Please make semicolons optional :)

**Comment by xabikos** [comment]
@dearfrankg Unfortunately there is no way to achieve something like this. The snippets should include semicolons or not.

**Comment by dearfrankg** [comment]
@xabikos thanks for the update.  I guess forking is the only answer.

**Comment by xabikos** [comment]
@dearfrankg based on my understanding yes.

**Comment by pcjmfranken** [comment]
I noticed that the extension [vscode-exports-autocomplete](https://github.com/capaj/vscode-exports-autocomplete) adds or removes semicolons based on eslint semicolon config setting ([relevant commit](https://github.com/capaj/vscode-exports-autocomplete/commit/af23d6bbd0620f489fd68bba3bcacbb68a351a9b)).

**Comment by xabikos** [comment]
@pcjmfranken vscode-exports-autocomplete is a full extension not just code snippets. You can execute regular JavaScript code. Code snippets is much simpler and you don't have this option. For example 
```
"reactClassComponent": {
    "prefix": "rcc",
    "body": "import React, { Component } from 'react';\n\nclass ${1:componentName} extends Component {\n\trender() {\n\t\treturn (\n\t\t\t<div>\n\t\t\t\t$0\n\t\t\t</div>\n\t\t);\n\t}\n}\n\nexport default ${1:componentName};",
    "description": "Creates a React component class with ES6 module system"
  },
```
this snippets creates the react class component. So we can't have this control. The only option to do this is to completely remove the semicolons from here. But then there will be some other people who like them.

**Comment by rachelslurs** [comment]
Wouldn't this be possible using an extension setting?
