### ISSUE TITLE
How to work with prop-types package?

### ISSUE THREAD

**Issue by lewis617** [xabikos/vscode-react#26]
When I enter 'rscp', I want to generate this:
```
import React from 'react';
import PropTypes from 'prop-types';

const ComponentName = props => {
  return (
    <div>

    </div>
  );
};

ComponentName.propTypes = {

};

export default ComponentName;
```

But, it will generate this code:
```
import React, { PropTypes } from 'react';

const ComponentName = props => {
  return (
    <div>

    </div>
  );
};

ComponentName.propTypes = {

};

export default ComponentName;
```

How to work with prop-types package?

**Comment by nbar1** [comment]
@lewis617 What you are asking for was checked in almost 2 months ago 12232fb. You may need to update your plugin.

**Comment by lewis617** [comment]
@nbar1  As you said, It really works when I updated my plugin. Now I think it's the problem of the VSCode, it didn't give a tip of updating this plugin. So I think the plugin is the latest version. Anyway, Thank you.
