### ISSUE TITLE
rcc code style guide & code format bug!

### ISSUE THREAD

**Issue by xyzdata** [xabikos/vscode-react#28]
> good code format

```jsx
import React, {Component} from 'react';

class componentName extends Component {
    render() {
        return(
            <div>
                {/* comments */}
            </div>
        );
    }
}

export default componentName;
```
> not too good

```jsx
import React, { Component } from 'react'

class componentName extends Component {
    render () {
        return (
            <div>
                
            </div>
        )
    }
}

export default componentName
```

**Comment by xyzdata** [comment]
# VSCode

##  language `javascript`

> react jsx format error <kbd>Ctrl + K</kbd> & <kbd>Ctrl + F</kbd>

![rrc-format-bug](https://user-images.githubusercontent.com/29531779/27627803-a6f92e2c-5c1f-11e7-8df0-4cc921e74e5a.gif)

##  language `javascriptreact`

> react jsx format OK & but, I can't using `rcc`  + <kbd>Tab</kbd>


![rrc-bug-format-ok](https://user-images.githubusercontent.com/29531779/27628019-4d43c0d0-5c20-11e7-85a1-a98a4522a261.gif)

**Comment by xgqfrms-GitHub** [comment]
#  <kbd> rcc </kbd> + <kbd>Tab</ kbd>

https://gist.github.com/xgqfrms-GitHub/a3c44b1cad00bc4a0f8d4c497e764ff1

**Comment by xyzdata** [comment]
https://github.com/xabikos/vscode-react/issues/28

**Comment by xgqfrms-GitHub** [comment]
# React Snippets

![image](https://user-images.githubusercontent.com/18028768/31304601-7b8d54fc-ab57-11e7-9954-e239fee37ded.png)

https://marketplace.visualstudio.com/items?itemName=xabikos.ReactSnippets
