### ISSUE TITLE
Incorporate $TM_FILENAME_BASE into component snippets

### ISSUE THREAD

**Issue by bpugh** [xabikos/vscode-react#33]
Vscode v1.16 added the snippet variable: $TM_FILENAME_BASE (https://code.visualstudio.com/updates/v1_16#_snippets). It resolves to the filename without extension so we could add it to the snippets for creating components to prepopulate the component name with the filename.
I'd be happy to submit a PR if you'd be willing to accept the change.

**Comment by xabikos** [comment]
@bpugh my apologies for the really late reply.

I missed the addition of the variable to be honest. It's really handy I have to admit and I would be more than happy to incorporate this change. 

If you could create a PR would be great, otherwise I will do it myself as soon as time permits.

**Comment by xabikos** [comment]
Addressed by #41
