### ISSUE TITLE
Make language -> file extension association configurable

### ISSUE THREAD

**Issue by mrchief** [xabikos/vscode-react#36]
A lot of folks use .js extensions for .jsx files. It'd be nice to have this configurable.

**Comment by xabikos** [comment]
I am not quite sure I understand what you mean.

As you can see [here](https://github.com/xabikos/vscode-react/blob/master/package.json#L29) the snippets are available for JavaScript language which normally have `.js` extension.

Feel free to explain a bit more if I miss something.

**Comment by mrchief** [comment]
Hmm, well at times the snippets stop working. So I was wondering if its due to the language settings.

E.g., if I type `imp` and tab out, VS code will complete it as `<imp></imp>`.

**Comment by xabikos** [comment]
This is not a problem with the snippets itself but rather how VS Code treats them.

An improvement to your issue could be to set the `"editor.snippetSuggestions": "top",` setting to always see the snippets on the top of the autocomplete list.

**Comment by mrchief** [comment]
I suspect that too. But is `"editor.snippetSuggestions": "top"` setting going to help with tab complete? I don't usually wait for the snippets dialog to load.

**Comment by xabikos** [comment]
So the problem is that you just want to type `imp` and trigger the snippet before the autocomplete pop up to appear? I am not sure we can solve this one.

**Comment by mrchief** [comment]
That and prevent any snippet turning into HTML. 

I'm realizing this may not be completely in your hands. Sublime Text never had this issue though. It worked beautifully out of the box - html tags were expanded as html and code snippets as respective code snippets. VSCode should be allowing that...
