### ISSUE TITLE
Add state to rcc

### ISSUE THREAD

**Issue by ridgekimani** [xabikos/vscode-react#38]
With react 16, state doesn't need to be created in the constructor. Therefore I would suggest upon creation of stateful components to be included
```javascript
export default class componentName extends Component {
  state  = {}
  render() {
    return (
      <div>
        
      </div>
    )
  }
}
```

**Comment by xabikos** [comment]
@ridgekimani I would happily change that but I don't see actually this change.

The example [here](https://reactjs.org/docs/state-and-lifecycle.html#adding-local-state-to-a-class)
initialize the state in the constructor which I consider a good approach
```javascript
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}
```

**Comment by xabikos** [comment]
I am closing this as I didn't get any feedback. If I missed something feel free to open it again.
