### ISSUE TITLE
Error on Dev Tools

### ISSUE THREAD

**Issue by elkinjosetm** [xabikos/vscode-react#39]
Every time I open the VSCode, I got this error on VS Code Dev Tools:

```
[{USER_PATH}/.vscode/extensions/xabikos.ReactSnippets-1.7.0]: Unknown language in `contributes.ReactSnippets.language`. Provided value: jsx
```

I already tryied uninstalling the extension, and installing it again, but right after installing it, shows up again.

**Comment by xabikos** [comment]
@elkinjosetm thanks for reporting this. It's not fixed as the [corresponding extension](https://marketplace.visualstudio.com/items?itemName=TwentyChung.jsx) is also removed from the marketplace.
