### ISSUE TITLE
Add static getDerivedStateFromProps(){}

### ISSUE THREAD

**Issue by ridgekimani** [xabikos/vscode-react#40]
With react 16.4 , `componentWillReceiveProps` will be deprecated and `getDerivedStateFromProps` will be used

**Comment by xabikos** [comment]
@ridgekimani thanks for the information of that. Really well appreciated.

This is a bit tricky as there are people that they won't migrate to 16.4 directly.
What I am thinking to do is to keep `componentWillReceiveProps` but add a deprecation comment and add a snippet for `getDerivedStateFromProps` with a clear comment that this works with react 16.4 and newer.

How this sounds to you?

**Comment by RusinovAnton** [comment]
@xabikos that sounds perfect! Do you need any help on this?
