### ISSUE TITLE
Is this compatible with React >16.2?

### ISSUE THREAD

**Issue by shamas** [xabikos/vscode-react#47]
The lifecycle changed significantly in react 16, but rcfc still uses all the old lifecycles; what's the plan for upgrading this?

**Comment by xabikos** [comment]
@shamas Thanks for bringing this up. 

I was a bot overloaded and miss this concept. I am going to release a new version of the snippets. But I think it's going to have breaking changes so will be a major version

**Comment by xabikos** [comment]
Closed as it's resolved by #71
