### ISSUE TITLE
Support propTypes defined as static class property

### ISSUE THREAD

**Issue by junkycoder** [xabikos/vscode-react#51]
Hi @xabikos.

thanks a lot for this project! I've using React Snippets about one week and It saved me a lot of time already. There is one thing - I'm already using static class properties but can't make a PR because my approach don't follow the official EcmaScript standard yet. And there is no way, how to customize your snippets.

**before**
```
class Example extends Component {        
        render() {
            return (
                <div>
                    
                </div>
            );
    }
}

Example.propTypes = {

};

export default Example;
```

I decided to create [this patch script](https://gist.github.com/junkycoder/5544e8338fc6a424ee010e1facb1c672) that can be used directly from the terminal, so I can share this method with you all here.

**after the patch**

```
class Example extends Component {
        static propTypes = {

        };
        
        render() {
            return (
                <div>
                    
                </div>
            );
    }
}

export default Example;
```

You can use this method for patching any of current snippets or to add some new ones...

**Comment by xabikos** [comment]
Hello @junkycoder and sorry for my late response.

I think creating a new snippet that has the propTypes as static property embedded in the class is the best approach. What do you think?

**Comment by xabikos** [comment]
I am closing this as I didn't get any feedback. Feel free to reopen it if necessary.
