### ISSUE TITLE
Can I assign these to keybindings?

### ISSUE THREAD

**Issue by simkessy** [xabikos/vscode-react#55]
How would I assign some of these to keybindings so instead of typing "anfn" I could do some custom command?

**Comment by xabikos** [comment]
I know it's too late to reply this one but [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets) you can see the official documentation on how to assign key bindings to snippets.

**Comment by xabikos** [comment]
I am closing this. Feel free to open it again if it becomes relevant.
