### ISSUE TITLE
How can I change the snippets?

### ISSUE THREAD

**Issue by ellvtr** [xabikos/vscode-react#61]
Great tool!

I prefer a different snippet for `rcc` than the one configured. How can I change it?

My preferred snippet:
```tsx
import * as React from "react";

export class MyComp extends React.Component {
  render() {
    return (
      <React.Fragment>
        <p>abc</p>
      </React.Fragment>
    );
  }
}
```

**Comment by sdustin** [comment]
You can create "user snippets" (under file > preferences > user snippets)
Just paste the same JSON as here and modify to your liking
https://github.com/xabikos/vscode-react/blob/master/snippets/snippets.json#L2

**Comment by xabikos** [comment]
I consider the answer sdustin posted as valid. 

I am closing this but feel free to open it again if you would like some addition info.
