### ISSUE TITLE
It's just a question

### ISSUE THREAD

**Issue by MrEfrem** [xabikos/vscode-react#64]
Why does the `reactStateless (rsc)` do  `export default` but the `flowStatelessComponent (fsc)` just do `export`?

**Comment by xabikos** [comment]
I don't have experience with the flow. I added those snippers as part of #52. Do you have a preference how this should be implemented? With default or how it's now?

**Comment by MrEfrem** [comment]
@xabikos I don't use `flow` anymore because I switched to Typescript.
