### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Dam9** [xabikos/vscode-react#69]
Issue Type: <b>Bug</b>

All extensions doesn't work... specially "Reactjs code snippets"

Extension version: 2.4.0
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by xabikos** [comment]
@Dam9  Could you provide some more info? Because everything looks fine when I tested after I upgrade to latest version (1.40.0) of VS code. No errors in console as well.

**Comment by xabikos** [comment]
I am closing this as no further info provided. Feel free to open it again if required.
